/// Stable route names used throughout app navigation.
abstract final class AppRoutes {
  static const welcome = 'welcome';
  static const teacherSetup = 'teacherSetup';
  static const teacherUnlock = 'teacherUnlock';
  static const teacherHome = 'teacherHome';
  static const teacherClasses = 'teacherClasses';
  static const teacherClassCreate = 'teacherClassCreate';
  static const teacherClassDetails = 'teacherClassDetails';
  static const teacherClassEdit = 'teacherClassEdit';
  static const teacherStudentList = 'teacherStudentList';
  static const teacherStudentDetails = 'teacherStudentDetails';
  static const teacherAttendance = 'teacherAttendance';
  static const teacherSettings = 'teacherSettings';
  static const teacherDeviceStatus = 'teacherDeviceStatus';
  static const bleScanner = 'bleScanner';
  static const attendanceResults = 'attendanceResults';
  static const studentSetup = 'studentSetup';
  static const studentHome = 'studentHome';
  static const studentAttendance = 'studentAttendance';
  static const studentDevice = 'studentDevice';
  static const studentProfile = 'studentProfile';
  static const shareSubjects = 'shareSubjects';
  static const addSubject = 'addSubject';
  static const teacherAttendanceAccessQr = 'teacherAttendanceAccessQr';
  static const attendanceAccessImport = 'attendanceAccessImport';
  static const attendanceOfficerHome = 'attendanceOfficerHome';
  static const attendanceOfficerScanner = 'attendanceOfficerScanner';
  static const attendanceOfficerResults = 'attendanceOfficerResults';
}
